name: CICD forest-admin
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "dev"

jobs:
  development-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ github.event.inputs.environment }}
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
